apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ui-services
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: ui-services
    spec:
      containers:
      - name: ui-services
        image: gcr.io/titan-185301/ui-services:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: ui-services
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ui-services